### ISSUE TITLE
Tool 4 requires two levels of selection

### ISSUE THREAD

**Issue by larnsce** [MoritzGold/BSF_app#3]
Not all options in "Substrate groups" have all six "Performance Indicators". 

For example: Substrate group "Food waste - Household" only has data for Performance indicator "larval_mg_DM" and "waste_reduction_perc_DM". 

What is needed here is a two level selection where based on the selected substrate group only the relevant performance indicator show up.

**Comment by MoritzGold** [comment]
Used updateCheckboxGroupInput() in tool4 to modify the possible selections for "Performance_indicator_tool4" (Cbeckbox 2) based on "Substrate_groups_tool4" (Checkbox 1)
